services:

  backend:
    build:
      context: ./dack-backend
    ports:
      - "5000:5000"
    volumes:
      - ./dack-backend:/dack-backend

  frontend:
    container_name: dack-frontend
    command: >
      sh -c "npm run dev"
    build:
      context: ./dack-frontend
    ports:
      - "3000:3000"

    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./dack-frontend:/dack-frontend
      - /dack-frontend/node_modules